# This is a basic workflow to help you get started with Actions
name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push: # Allows you to run this workflow manually from the Actions tab

  workflow_dispatch:

    # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v4

    - name: set up
      run: |
        cp -r ./src ./cicd
        cp api.py ./cicd/api.py

    - name: Run server
      run: |
        cd ./cicd
        USERID=$(id -u) GID=$(id -g) docker compose up --build -d
      env:
        PROXMOX_URL: ${{ secrets.PROXMOX_URL }}
        API_TOKEN_ID: ${{ secrets.API_TOKEN_ID }}
        API_TOKEN_SECRET: ${{ secrets.API_TOKEN_SECRET }}
        NODE: ${{ vars.NODE }}
        TEMPLATE_ID: ${{ vars.TEMPLATE_ID }}
        NETWORK_BRIDGE: ${{ vars.NETWORK_BRIDGE }}
        VM_GW: ${{ vars.VM_GW }}
        ALLOW_ORIGINS: ${{ vars.ALLOW_ORIGINS }}
